
### | create service
POST http://localhost:9000/api/v1/service
Content-Type: application/json

{
    "name": "Sidocal Service",
    "price": 20.70
}

### | update service
PATCH http://localhost:9000/api/v1/service/bfd4446a-d44b-427c-b227-d1325a58996d
Content-Type: application/json

{
    "name": "GONALITIC Service",
    "price": 20.90
}

### | delete service
DELETE http://localhost:9000/api/v1/service/bfd4446a-d44b-427c-b227-d1325a58996d

### | get service
GET http://localhost:9000/api/v1/service

### | get service by Id
GET http://localhost:9000/api/v1/service/1fa14fa3-6bb1-4a69-87ec-2caab217b006

#--------

//-------------
### | signup admin
POST http://localhost:9000/api/v1/admin/signup
Content-Type: application/json

{
    "email":     "johndoeiiioi@gmail.com",      
  	"full_name": "John Doe",
  	"password":  "5554321Acomid!"
}

### | signin admin
POST http://localhost:9000/api/v1/admin/signin
Content-Type: application/json

{
    "email":     "johndoe@gmail.com",      
  	"password":  "5554321Acomid!"
}

### | change practitioner status
POST http://localhost:9000/api/v1/admin/status/fbb1ea28-69ae-4f77-93de-6a487560ceef
Content-Type: application/json

{
    "status": "approved"     
}

### | logout admin
POST http://localhost:9000/api/v1/admin/logout/196f97cc-7fa3-4783-ab0b-74dd8a3c9753
Content-Type: application/json

### | all admin
GET http://localhost:9000/api/v1/admin


// ------------- //

### | Search Patient
GET http://localhost:9000/api/v1/patient/search?skip=2&take=2


### | Search Practitioners
GET http://localhost:9000/api/v1/practitioner/search?skip=0&take=2

### | create appointment
POST http://localhost:9000/api/v1/appointment
Content-Type: application/json

{
  "title": "Annual Checkup 2024",
  "date": "2024-02-28T10:30:00Z",
  "time": "2024-02-28T11:00:00Z",
  "practitionerId": "70f3b6e8-3958-462f-a82c-69d2de928995",
  "patientId": "4d80a0fb-539f-4191-85ac-c3390c43483d",
  "service": "General Health Assessment",
  "comment": "Patient requests a thorough checkup, including blood work and physical exam.",
  "tc": true,
  "payment_completed": false,
  "status": "pending",
  "expiry": "2024-02-28T12:30:00Z"
}


### | update appointment
PATCH http://localhost:9000/api/v1/appointment/8b4965e7-55d0-4732-aacf-7a6ecb3c3e17
Content-Type: application/json

{
  "title": "Annual Checkup 2025",
  "date": "2024-02-28T10:30:00Z",
  "time": "2024-02-28T11:00:00Z",
  "practitionerId": "70f3b6e8-3958-462f-a82c-69d2de928995",
  "patientId": "10239a7f-a8bb-4ace-aaec-1b267ffcba98",
  "service": "General Health Assessment",
  "comment": "Patient requests a thorough checkup, including blood work and physical exam.",
  "tc": true,
  "payment_completed": false,
  "status": "pending",
  "expiry": "2024-02-28T12:30:00Z"
}

### | delete appointment
DELETE http://localhost:9000/api/v1/appointment/224d3cc4-031b-45ad-9e7f-343c3f948492

### | get appointment
GET http://localhost:9000/api/v1/appointment

### | get appointment by Id
GET http://localhost:9000/api/v1/appointment/8b4965e7-55d0-4732-aacf-7a6ecb3c3e17

#-----

### | create specialisation
POST http://localhost:9000/api/v1/specialisation
Content-Type: application/json

{
    "name": "Nasal Spectometry"
}

### | update specialisation
PATCH http://localhost:9000/api/v1/specialisation/1821254-234f-45c7-9e7c-4100ec8efcc0
Content-Type: application/json

{
    "name": "Scan Spectrometry"
}

### | delete specialisation
DELETE http://localhost:9000/api/v1/specialisation/08328d2d-19a5-4bc1-a8bb-c6467632bcd4

### | get specialisations
GET http://localhost:9000/api/v1/specialisation

### | get specialisation by Id
GET http://localhost:9000/api/v1/specialisation/8328d2d-19a5-4bc1-a8bb-c6467632bcd4

#-----

### | create hospital
POST http://localhost:9000/api/v1/hospital
Content-Type: application/json

{
    "name": "Bethel-1 Hospital"
}

### | update hospital
PATCH http://localhost:9000/api/v1/hospital/f710f2a8-0a31-4874-9c2d-dc37bdfefc38
Content-Type: application/json

{
    "name": "Bel"
}

### | delete hospital
DELETE http://localhost:9000/api/v1/hospital/e2997838-ca58-478a-a7c8-16643d48dda1

### | get hospitals
GET http://localhost:9000/api/v1/hospital

### | get hospital by Id
GET http://localhost:9000/api/v1/hospital/d6d6b955-49e7-46a1-820e-2d12c9a71028

#--------

### | signup practitioners
POST http://localhost:9000/api/v1/practitioner/signup
Content-Type: application/json

{
    "email": "johntdoiviiiiiiiiirieeioiio@gmail.com",
    "full_name": "xoi vin",
    "password": "StrongPassword123!",
    "dob": "1990-01-01T00:00:00Z",
    "pob": "New York",
    "img_url": "",
    "digital_address": "123 Main Street",
    "contact": "123-456-7890",
    "id_type": "ghana_card",
    "id_number": "1234567890",
    "qualification": "Doctor of Medicine",
    "licence_number": "123ABC",
    "specialisations": [ "07da2a00-1a30-444f-b173-4734538a85fc"],
    "hospitals": [ "328478f6-30ec-4cff-80a6-1e66f66135d3"],
    "verified": true
}

### | signin practitioner
POST http://localhost:9000/api/v1/practitioner/signin
Content-Type: application/json

{
    "email": "johntdoiviiiiiiiiirieeioiio@gmail.com",
    "password": "StrongPassword123!"
}

### | logout practitioner
POST http://localhost:9000/api/v1/practitioner/logout/bd14bb53-dd0b-404d-98d0-98e058251d8e
Content-Type: application/json

### | signup patient
POST http://localhost:9000/api/v1/patient/signup
Content-Type: application/json

{
    "email":     "johndoeiv@gmail.com",      
  	"full_name": "John Doe",
  	"password":  "5554321Acomid!"
}

### | signin patient
POST http://localhost:9000/api/v1/patient/signin
Content-Type: application/json

{
    "email":     "johndoe@gmail.com",      
  	"password":  "5554321Acomid!"
}

### | logout patient
POST http://localhost:9000/api/v1/patient/logout/196f97cc-7fa3-4783-ab0b-74dd8a3c9753
Content-Type: application/json




























































































###
# update project
PATCH  http://localhost:9000/mui-project-service/api/v1/projects/c828301b-2d77-440f-9ca6-396fb679d9d1
Content-Type: application/json

{
    "user_id": "d970b214-0dd7-4855-86c4-2fda176dd432",
	"project_name": "MOTHER 450",
	"description": "MOTHER-22 CONTENT"
}

###
# delete project
DELETE  http://localhost:9000/mui-project-service/api/v1/projects/096f7718-0b98-40db-a50f-2f7cf70a2a8b

###
# fetch all projects
GET  http://localhost:9000/mui-project-service/api/v1/projects
Content-Type: application/json

###
# fetch all projects by ID
GET  http://localhost:9000/mui-project-service/api/v1/projects/87913193-a649-4688-8fb8-53b507d19f32
Content-Type: application/json

###
GET  http://localhost:9000/mui-project-service/api/v1/admin
Content-Type: application/json
# Authorization: 

# {
#     "ID": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
# 	"title": "TOMBA THREAD",
# 	"content": "TOMBA CONTENT"
# }


